#!/usr/bin/env bash

set -eu

if ! docker inspect --type=image ipmitool:latest &>/dev/null; then
  CONTEXT="$(mktemp -d)"
  trap "rm -rf $CONTEXT" SIGINT SIGTERM EXIT
  echo -e 'FROM quay.io/experimentalplatform/ubuntu:latest\nRUN apt-get update && apt-get install -y -q --no-install-recommends ipmitool && apt-get clean && rm -rf /var/lib/apt/lists/*' > "$CONTEXT/Dockerfile"
  docker build -t ipmitool:latest "$CONTEXT"
fi

if [ $# -gt 0 ] && [ "$1" == "lockall" ]; then
  SCRIPT='
for i in $(seq 1 63); do
  ipmitool user disable $i
done'
  exec docker run -i --rm --privileged -v /dev/:/dev/:rw ipmitool:latest sh -c "$SCRIPT"
fi

exec docker run -i --rm --privileged -v /dev/:/dev/:rw ipmitool:latest ipmitool $@
