#!/usr/bin/env bash

set -eu

if ! docker inspect --type=image ipmitool:latest &>/dev/null; then
  CONTEXT="$(mktemp -d)"
  trap "rm -rf $CONTEXT" SIGINT SIGTERM EXIT
  echo -e 'FROM alpine\nRUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories\nRUN apk update && apk add ipmitool && rm -rf /var/cache/apk/*' > "$CONTEXT/Dockerfile"
  docker build -t ipmitool:latest "$CONTEXT"
fi

if [ $# > 0 ] && [ "$1" == "lockall" ]; then
  SCRIPT='
for i in $(seq 1 63); do
  ipmitool user disable $i
done'
  exec docker run -it --rm --privileged -v /dev/:/dev/:rw ipmitool:latest sh -c "$SCRIPT"
fi

exec docker run -it --rm --privileged -v /dev/:/dev/:rw ipmitool:latest ipmitool $@
