#!/usr/bin/env bash

set -eu

if [ "$(id -u)" != "0" ]; then
  exec sudo $0 $@
fi

print_help() {
  echo "usage: $0 [help|password]"
}

if [ "$#" -eq 0 ]; then
  echo "Enter New Master Password (hidden): "
  read -r -s pass
  echo -n "$pass" > /etc/protonet/system/ssh/password
  exit 0
fi

if [ "$1" == "help" ]; then
  print_help
  exit 0
elif [ "$1" == "" ]; then
  echo "Password cannot be empty"
  exit 1
else
  echo -n "$1" > /etc/protonet/system/ssh/password
fi

