#!/usr/bin/env bash

set -eu

if [ "$(id -u)" != "0" ]; then
  exec sudo $0 $@
fi

print_help() {
  echo "usage: $0 [help|password]"
}

if [ "$#" != "1" ]; then
  print_help
  exit 1
fi

if [ "$1" == "help" ]; then
  print_help
  exit 0
elif [ "$1" == "" ]; then
  echo "Password cannot be empty"
  exit 1
else
  echo "$1" > /etc/protonet/system/ssh/password
fi

