#!/usr/bin/env bash

set -eu

if ! docker inspect --type=image tcpdump:latest &>/dev/null; then
  CONTEXT="$(mktemp -d)"
  trap "rm -rf $CONTEXT" SIGINT SIGTERM EXIT
  echo -e 'FROM alpine\nRUN apk update && apk add tcpdump && rm -rf /var/cache/apk/*' > "$CONTEXT/Dockerfile"
  docker build -t tcpdump:latest "$CONTEXT"
fi
exec docker run -it --rm --net host tcpdump:latest tcpdump $@

